services:
  openbao-dev:
    container_name: openbao-dev
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.vault.dev
    ports:
      - "127.0.0.1:8200:8200"  # Alleen lokaal toegankelijk op poort 8200
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    mem_swappiness: 0  # Voorkomt swapping voor betere prestaties en veiligheid
    command: server -dev
