version: '3.7'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault-dev
    environment:
      - VAULT_LOCAL_CONFIG
      - VAULT_TLS_DISABLE
    env_file:
      - .env.vault.dev
    ports:
      - "127.0.0.1:49281:8200"  # Alleen lokaal toegankelijk op poort 49281
    volumes:
      - ./vault/data:/vault/file
      - ./vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    command: server -config=/vault/config/vault-config.hcl
