services:
  vault:
    image: quay.io/openbao/openbao:2.3.1
    container_name: vault-dev
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root-token-dev
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "127.0.0.1:49281:8200"  # Alleen lokaal toegankelijk op poort 49281
    volumes:
      - ./scripts:/opt/bin  # Scripts beschikbaar in container
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    # Geen command betekent dat het in dev-mode start
